### ISSUE TITLE
Sugestii

### ISSUE THREAD

**Issue by arlekyn2** [xngsrs/myhobby#23]
Salutare,

Am 2 sugestii pt imbunatatirea pluginului:
1) Sa preia mai multe de la Trakt (trending, popular etc... in afara de progress) + ar fi buna si optiunea de a afisa sau nu "unaired episodes" la progress.
2) Stiu ca asta ar fi mult mai complicat... dar Filelist are acum api... si suporta inclusiv cautare pe season/episode. Eu nu sunt programator, am incercat eu ceva pentru elementum burst, dar nu mi-a iesit:

https://github.com/elgatito/script.elementum.burst/issues/167

Poate s-ar putea incerca ceva implementare in MRSP (cautare pe baza FL api)? 
MRSP e singurul addon pe care-l stiu ca mai functioneaza cu FL search - doar ca nu cauta (sau nu filtreaza) rezultatele dupa sezon/episod

**Comment by xngsrs** [comment]
Salut,
1. Chiar ma gandeam recent ca poate ar trebui sa implementez si categoriile de care ziceai, din trakt, desi mi s-au parut absolut inutile, motiv pentru care nu am facut-o pana acum. O sa fac si asta. Nu stiu oricum cat de mult o sa reziste optiunea de acum din trakt,
in cazul in care sunt mai multi care o folosesc (se fac extraordinar de multe requesturi in thetvdb in cazul in care utilizatorul are multe seriale in curs de urmarire, de aia se incarca si asa greu), asa ca va trebui sa gasesc variante, in timp. 

2. Nu ar fi deloc complicat sa implementez api pentru filelist, eventual cu optiune in setari pentru scrapper sau api, ca la subtitrari regielive. Ar fi doar problema de documentatie, ce au pe site e foarte sumar( de exemplu nu stiu ce fel de tipuri de action sunt acceptate) dar prin trial and error se rezolva. 
      Cautarea functioneaza foarte bine dupa sezon sau episod, trebuie doar sa cauti de exemplu "game of thrones s04e03" pentru episodul 3 din sezonul 4 sau "game of thrones s04" pentru cautarea tuturor episoadelor sau packurilor cu sezonul 4.
 Momentan, din trakt, asa cum l-am facut acum (fiind facut pentru uz personal), trebuie sa activezi meniul contextual si sa dai clic pe "cauta variante" , iti va aparea keyboardul cu termenul exact de cautare pe care vei putea sa il modifici daca vrei, dar o sa fac asta ca actiune implicita, deoarece acum la actiune implicita pe clic cauta doar numele serialului, fara episod sau sezon.

Pe scurt, cautarea merge bine dupa sezon si episod, rezultatele sunt aranjate dupa numarul de seederi din prima pagina a rezultatelor de pe fiecare site. Restul voi face, in timp.
P.S. foloseste meniul contextual ( activat de clic dreapta, sau apasat tasta meniu pe telecomanda, sau tinut clic lung pe element, in functie de device), sunt multe chestii ascunse.

**Comment by arlekyn2** [comment]
Multumesc f mult pt. un raspuns asa rapid! In primul post am uitat sa precizez ca ai facut o treaba extraordinara cu acest addon (MRSP) in special, dar si cu restul!
Referitor la cautarea sezon/episod, da, am observat si eu ca la cautarea manuala, merge filtrul. In context n-am incercat, vazusem optiunea de cautare variante, dar n-am testat sa vad ce e. Chiar si asa, nu este ideal (in cazul meu) pentru ca meniul de context nu apare in widget-ul de pe interfata. Adica, eu am pus widget cu MRSP - trakt (adica trakt progress) in interfata pt a fi la doar un click distanta de un episode search, si fac search-ul doar dupa show name. Daca vreau search exact am varianta sa fac search manual din addon.
Referitor la celelalte categorii din trakt, cred ca-s utile. Spre ex, celelalte 2 widgets in interfata la mine sunt "Trakt trending" (luat momentan din elementum) pt filme si seriale. Asa vad imediat cand apar filme sau seriale noi - pt ca intra aproape imediat dupa lansare in primele pozitii la trending.
Am si o intrebare: foloseste la ceva torrenter v3? L-am vazut in repo, l-am instalat, dar MRSP nu l-a recunoscut ca "torrenter" si mi-a cerut sa instalez v2. De mers, merge bine si v2... cand vrea! Cred ca e ceva in neregula la mine totusi (am coreelec) pentru ca unele optiuni merg "pe invers" (de ex, marcarea ca vizionat catre trakt a mers dupa ce am dezactivat-o in mrsp... iar seed dupa vizionare face doar uneori, cu optiunea debifata in torrenter, dar activa in MRSP) si cand vrea, cand nu vrea sa faca seed dupa vizionare :) Oricum, dupa fiecare vizionare primesc un "torrenter error - check logs".
Azi dimineata, de ex, am dat drumul de 2-3 ori la vizionare si am oprit vizionarea... pt a face unele torrente sa stea la seed (fusesera complet descarcate/vizionate ieri). In fine, revin la intrebare, ajuta cu ceva acel torrenter v3 din repo?

**Comment by xngsrs** [comment]
Am inteles problema ta referitoare la widget. Initial nu am facut addonul cu torrenti si chestiile din trakt trebuiau sa gaseasca la clic ce era in favorite. Pe site-urile online romanesti e aproape imposibil sa gasesti un model de cautare pe sezon si episod si varianta mea a fost sa ia dupa nume ce era in favorite, apoi ma duceam al episodul care trebuia. Apoi am bagat torrentii si asa am ajuns la "cauta variante", chestie care imi permitea sa caut cum vroiam, fara prea mult scris din telecomanda. 
Torrenter nu e facut de mine, face parte dintr-un depozit pe care eu l-am adaugat complementar la depozitul meu. Cel care a preluat respectivul depozit a incercat probabil sa faca ceva pentru nevoile lui, asa a ajuns la **torrenter v3, inutil pentru MRSP,** oricum. 
  Fiind facut pentru mine, am modificat putin torrenter pentru a-mi satisface nevoile addonului (de aia l-am introdus la mine in depozit, modificat ), probabil ca nu am modificat peste tot, deoarece combinatia folosita de mine mi s-a parut cea mai ok. 
  Deci, ca sa functioneze corect, setarile in torrenter folosite de mine (cele principale) sunt: 
     1. P2P Network -> 
                                 P2P Player : Torrent2HTTP
                                 Keep downloaded files: Delete Files
     2. Torrent-client -> 
                                 Save path: Default
                                 Torrent Client: Transmission
     3. Hentai(fine-tunning) ->
                                 P2P Player : Torrent2HTTP

Marcarea ca vizionat in trakt ar trebui dezactivata daca folosesti alt addon pentru asta (cum ar fi Trakt).
Seed-ul dupa vizionare merge cu setarile de mai sus, numai dupa ce torrentul a trecut de 20% download in timpul vizionarii si daca trakerul de torrent are setat seed in torrenter sau transmission.
Eu in coreElec folosesc numai transmission pentru seed dupa vizionare, de asta exista si transmission la mine in depozit, dar trebuie facut un mic hack pentru a porni o data cu sistemul: in shell, in coreelec trebuie date comenzile: 
                    ```
                CoreELEC:~ #   ln -s /storage/.kodi/addons/service.downloadmanager.transmission/system.d/service.downloadmanager.transmission.service /storage/.config/system.d/service.downloadmanager.transmission.service
                 CoreELEC:~ #   systemctl daemon-reload
                 CoreELEC:~ #   systemctl enable service.downloadmanager.transmission.service
                 CoreELEC:~ #   systemctl start service.downloadmanager.transmission.service
```
  **In shell-ul coreelec intri cu orice client ssh, username root si parola coreelec**. 
Interfata transmission web o gasesti la **http://ip-ul-aparatului-tau-cu-coreelec:9091** , dar este si pentru kodi chiar in addonul "Transmission" care acum are versiunea 8.0.2a.
Dupa ce vezi ca functioneaza transmission, poti sa folosesti doar optiunile "seed in transmission" fara probleme, de preferat sa testezi intai cu un tracker public :).

**Comment by arlekyn2** [comment]
Dap, am si addonul trakt, inseamna ca d-aia a mers cand am lasat optiunea de marcare debifata.
Am incercat ceva cu transmission, dar din ce-mi amintesc, primul instalat (cred ca cel din repo, dar nu-s sigur) n-a mers - in torrenter dadea connection failed. Apoi am citit pe undeva ca pt libre/coreelec trebuie folosit cel din Thoradia repo. L-am instalat pe acela, pornea. Problema a fost ca nu facea seed pe FL... am intrat pe interfata web si spre surprinderea mea, trackerul dadea un mesaj de eroare de genul "client is not whitelisted".
In final, am gasit o metoda de a face seed dupa vizionare (in timpul vizionarii se face seed mereu, nu am probleme). La final, daca nu ramane seeding activat (asta verific in snatchlist pe FL), din context, dau "download cu torrenter". Pana acum se pare ca merge. Clientul face verificarea fisierului (fiind deja descarcat in timpul vizionarii) si apoi... il pune la seed.
Oricum, as incerca si cu setarile de mai sus, dar ma tem sa nu primesc aceeasi eroare de la FL (sa nu aiba transmission whitelisted).
Sa inteleg ca setarea asta din torrenter: Keep downloaded files: Delete Files
este ignorata/suprascrisa de MRSP (sa zicem "global seed cu transmission" on)?
Multumesc din suflet pentru ajutor!

**Comment by arlekyn2** [comment]
Salutare din nou, o rugaminte am, daca se poate. Cred ca n-ar strica un fisier care sa defineasca MRSP-ul ca "player" pentru open meta addon. Mai exact... sa-l putem folosi pentru a cauta filmul/show-ul afisat de open meta cu MRSP:
https://github.com/a4k-openproject/plugin.video.openmeta/wiki/Writing-an-OpenMeta-player

**Comment by arlekyn2** [comment]
Am testat varianta cu transmission activat in ssh si merge. Face seed si pe FL (testat), spre deosebire de transmission v3-beta, ultima din thoradia repo (acela are avantajul ca nu necesita ssh commands, dar nu e pe whitelist la FL). Pe thoradia au si v2.4, dar acea nu s-a activat nici din SSH. 
Am 2 intrebari legate de setari la transmission:
1) Daca in torrenter am pus locatia de savare torrents pe un HDD extern, in transmission mai trebuie sa umblu la setari? (default are un path cu downloads/...)
2) Pot adauga manual in transmission torrentele salvate deja (inainte de instalare/activare transmission) pe HDD-ul extern? Mi-e teama ca daca le adaug manual direct in transmission, va incerca sa re-descarce fisierele folosind setarile lui (momentan sunt cele default... adica memoria interna a box-ului.. cred)

**Comment by arlekyn2** [comment]
Salutare, un pic de ajutor cu open meta chair ar fi binevenit! Eu am incercat fel si fel de variante, dar nu merg. De ex:

"link"      : "plugin://plugin.video.romanianpack/?action=searchSites&query={title_+}",
    "steps"     : [ "@keyboard:{title}", "{title}" ]

Am incercat si sa adaugg la steps "searchSites", nu merge.
Cu siguranta "link" nu este bine determinat, dar n-am nici ce-a mai mica idee cum ar fi corect.
Ideal ar fi sa foloseasca functia de "cautare manuala" din MRSP cu ajutorul virtual kb (banuiesc).

**Comment by softusgsm** [comment]
Dupa ultimul update 57b in filmeonline2016 nu mai este nici o sursa

**Comment by xngsrs** [comment]
> Dupa ultimul update 57b in filmeonline2016 nu mai este nici o sursa

nu are legatura actualizarea, cu filmeonline2016. Au schimbat site-ul, o sa fac un update curand.

**Comment by xngsrs** [comment]
> Salutare, un pic de ajutor cu open meta chair ar fi binevenit! Eu am incercat fel si fel de variante, dar nu merg. De ex:
> 
> "link" : "plugin://plugin.video.romanianpack/?action=searchSites&query={title_+}",
> "steps" : [ "@keyboard:{title}", "{title}" ]
> 
> Am incercat si sa adaugg la steps "searchSites", nu merge.
> Cu siguranta "link" nu este bine determinat, dar n-am nici ce-a mai mica idee cum ar fi corect.
> Ideal ar fi sa foloseasca functia de "cautare manuala" din MRSP cu ajutorul virtual kb (banuiesc).

Salut, nu este treaba mea sa fac openmeta sa mearga. Asta e treaba utilizatorilor, daca ii intereseaza. Sincer sa fiu, openmeta mi se pare ceva absolut inutil, de aia nici nu ma intereseaza. Mi se pare mult mai ok sa iti cauti filmele pe cinemagia, din addon. Am bagat si niste filtre dupa nota, popularitate...etc, dar o sa apara la urmatorul update, nu am avut inca timp sa il pun online.
Ca sa iti raspund totusi la ceva, cautarea in mrsp se face in mai multe moduri, unul din ele este:
`plugin://plugin.video.romanianpack/?action=searchSites&searchSites=cuvant&cuvant=aici_pui_cuvintele_pentru_cautare_urlencoded`
Am citit toate mesajele tale, dar nu am avut cand sa raspund la ele.

**Comment by arlekyn2** [comment]
Multumesc pentru ajutor! Acum incerc sa corectez link-ul de query, sa vad ce iese :)

**Comment by softusgsm** [comment]
> > Dupa ultimul update 57b in filmeonline2016 nu mai este nici o sursa
> 
> @softusgsm
> nu are legatura actualizarea, cu filmeonline2016. Au schimbat site-ul, o sa fac un update curand.

Ba are sigur. Am instalat mrsp din T4K grup adica vers 1.0.45 si functioneaza filmeonline2016.

**Comment by xngsrs** [comment]
> Ba are sigur. Am instalat mrsp din T4K grup adica vers 1.0.45 si functioneaza filmeonline2016.

Atunci e bine, poti folosi versiunea aia

**Comment by arlekyn2** [comment]
Am facut ceva progres cu openmeta, dar m-am blocat. Poate se gaseste cineva priceput si amabil sa ajute.
Am reusit sa fac scriptul sa nu mai fie "invalid player", mai mult... face cautarea, gaseste rezultate, dar apoi pare sa faca un fel de procesare a lor ... si da error: no video file found.
Scriptul este acum:

{
 "name"         : "[COLOR FF0084FF]MRSP[/COLOR]",
 "id"           : "romanianpack",
 "movies"       : [[{"link": "plugin://plugin.video.romanianpack/?action=searchSites&amp;searchSites=noua&amp;noua={title_+}&amp",
 "steps"     : [ "keyboard:{title}", "{title}" ],
 "action"    : "PLAY" }]],
 "tvshows"      : [[{"link": "plugin://plugin.video.romanianpack/?action=searchSites&amp;searchSites=noua&amp;noua={clearname_+}&amp",
 "steps"     : [ "keyboard:{clearname}", "{clearname}", ".* {season}", "{episode}" ],
 "action"    : "PLAY" },
                    {"link": "plugin://plugin.video.romanianpack/?action=searchSites&amp;searchSites=noua&amp;noua={clearname_+}&amp",
 "steps"     : [ "keyboard:{clearname}", "{clearname}", "{episode}" ],
 "action"    : "PLAY" },
                    {"link": "plugin://plugin.video.romanianpack/?action=searchSites&amp;searchSites=noua&amp;noua={clearname_+}&amp",
 "steps"     : [ "keyboard:{clearname}", "{clearname}", "{clearname}", "{episode}" ],
 "action"    : "PLAY" }]]
}

Kodi log arata asa (dupa o cautare):

2020-02-13 06:10:40.426 T:3047146304   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/usr/lib/python2.7/threading.py", line 754, in run
                                              File "/storage/.kodi/addons/script.extendedinfo/resources/lib/DialogBaseInfo.py", line 116, in get_youtube_vids
                                                result = YouTube.search_youtube(search_str, limit=10)
                                              File "/storage/.kodi/addons/script.extendedinfo/resources/lib/YouTube.py", line 78, in search_youtube
                                                videos = handle_youtube_videos(results['items'], extended=extended)
                                            KeyError: 'items'
2020-02-13 06:10:41.382 T:3393975104 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.service/resources/lib/webservice.py", line 272, in handle_request
                                                self.send_error(404, 'No image was found')
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 407, in send_response
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
                                              File "/usr/lib/python2.7/socket.py", line 328, in write
                                              File "/usr/lib/python2.7/socket.py", line 307, in flush
                                            error: [Errno 32] Broken pipe
2020-02-13 06:10:41.382 T:3393975104   ERROR: Skin Helper Service --> Exception in resources.lib.webservice ! --> [Errno 32] Broken pipe
2020-02-13 06:10:44.367 T:3256517440   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/AGBO.png
2020-02-13 06:10:44.368 T:3256517440   ERROR: DoWork - Direct texture file loading failed for resource://resource.images.studios.white/MWM Studios.png
2020-02-13 06:10:45.603 T:3047146304 WARNING: Attempt to use invalid handle -1
2020-02-13 06:10:52.441 T:3047146304 WARNING: Previous line repeats 1 times.
2020-02-13 06:10:52.441 T:3047146304   ERROR: 2020-02-13 06:10:52,440 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 720p BluRay DD5 1 x264-playHD  [COLOR green]Filme HD-RO[/COLOR] (5 25GB) [S/L: 603/3]
2020-02-13 06:10:52.443 T:3047146304   ERROR: 2020-02-13 06:10:52,442 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 1080p BluRay DD5 1 x264-playHD  [COLOR green]Filme HD-RO[/COLOR] (11 45GB) [S/L: 300/2]
2020-02-13 06:10:52.444 T:3047146304   ERROR: 2020-02-13 06:10:52,444 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 BDRip DD5 1 x264-playSD  [COLOR green]Filme SD[/COLOR] (1 39GB) [S/L: 177/1]
2020-02-13 06:10:52.445 T:3047146304   ERROR: 2020-02-13 06:10:52,445 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - 21 Bridges 2019 BDRip x264-AAA  [COLOR green]Filme SD[/COLOR] (519 86MB) [S/L: 141/39]
2020-02-13 06:10:52.446 T:3047146304   ERROR: 2020-02-13 06:10:52,446 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 720p BluRay DD5 1 x264-CRiSC  [COLOR green]Filme HD-RO[/COLOR] (5 29GB) [S/L: 117/2]
2020-02-13 06:10:52.447 T:3047146304   ERROR: 2020-02-13 06:10:52,447 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - 21 Bridges 2019 1080p BluRay x264-AAA  [COLOR green]Filme HD[/COLOR] (7 75GB) [S/L: 90/12]
2020-02-13 06:10:52.448 T:3047146304   ERROR: 2020-02-13 06:10:52,447 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 2160p WEB-DL DD+5 1 H 265-BLUTONiUM  [COLOR green]Filme 4K[/COLOR] (15 27GB) [S/L: 86/1]
2020-02-13 06:10:52.449 T:3047146304   ERROR: 2020-02-13 06:10:52,448 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - 21 Bridges 2019 720p BluRay x264-AAA  [COLOR green]Filme HD[/COLOR] (4 43GB) [S/L: 81/13]
2020-02-13 06:10:52.450 T:3047146304   ERROR: 2020-02-13 06:10:52,449 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 1080p Remux AVC DTS-HD MA 5 1-playBD  [COLOR green]Filme Blu-Ray[/COLOR] (24 47GB) [S/L: 52/0]
2020-02-13 06:10:52.450 T:3047146304   ERROR: 2020-02-13 06:10:52,450 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - 21 Bridges 2019 720p BluRay DD5 1 x264-iFT  [COLOR green]Filme HD[/COLOR] (5 64GB) [S/L: 30/1]
2020-02-13 06:10:52.451 T:3047146304   ERROR: 2020-02-13 06:10:52,451 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - [COLOR lime]FREELEECH[/COLOR] 21 Bridges 2019 1080p Blu-ray AVC DTS-HD MA 5 1-DiSRUPTION  [COLOR green]Filme Blu-Ray[/COLOR] (28 56GB) [S/L: 20/1]
2020-02-13 06:10:52.452 T:3047146304   ERROR: 2020-02-13 06:10:52,452 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FileList[/COLOR] - 21 Bridges 2019 1080p BluRay DTS x264-iFT  [COLOR green]Filme HD[/COLOR] (12 63GB) [S/L: 19/0]
2020-02-13 06:10:52.453 T:3047146304   ERROR: 2020-02-13 06:10:52,453 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - [COLOR lime]FREE[/COLOR] 21 Bridges 2019 1080p BluRay x264 RoSub-AAA  [COLOR green]Filme HD-RO[/COLOR] (7 64GB) [S/L: 10/0]
2020-02-13 06:10:52.454 T:3047146304   ERROR: 2020-02-13 06:10:52,454 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - [COLOR lime]FREE[/COLOR] 21 Bridges 2019 1080p HC WEB-DL AAC 2 0 x264 RoSub-CMRG  [COLOR green]Filme HD-RO[/COLOR] (5 41GB) [S/L: 5/0]
2020-02-13 06:10:52.455 T:3047146304   ERROR: 2020-02-13 06:10:52,455 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - 21 Bridges 2019 720p HDCAM RoSub-GETB8  [COLOR green]Filme SD-RO[/COLOR] (2 09GB) [S/L: 2/0]
2020-02-13 06:10:52.456 T:3047146304   ERROR: 2020-02-13 06:10:52,456 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - 21 Bridges 2019 HDRip XviD AC3 RoSub-EVO  [COLOR green]Filme SD-RO[/COLOR] (1 38GB) [S/L: 2/0]
2020-02-13 06:10:52.457 T:3047146304   ERROR: 2020-02-13 06:10:52,456 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - [COLOR lime]FREE[/COLOR] 21 Bridges 2019 720p HDCAM AC3 RoSub-F1  [COLOR green]Filme SD-RO[/COLOR] (2 09GB) [S/L: 2/0]
2020-02-13 06:10:52.467 T:3047146304   ERROR: 2020-02-13 06:10:52,457 - DEBUG - [plugin.video.openmeta] matching pattern 21 Bridges to label [COLOR red]FluxZone[/COLOR] - [COLOR lime]FREE[/COLOR] 21 Bridges 2019 1080p WEB-DL DD5 1 H264-FGT  [COLOR green]Filme HD-RO[/COLOR] (3 46GB) [S/L: 1/0]
2020-02-13 06:11:33.786 T:3393975104 WARNING: Skin Helper Service --> Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.skin.helper.service/resources/lib/webservice.py", line 272, in handle_request
                                                self.send_error(404, 'No image was found')
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 365, in send_error
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 407, in send_response
                                              File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
                                              File "/usr/lib/python2.7/socket.py", line 328, in write
                                              File "/usr/lib/python2.7/socket.py", line 307, in flush
                                            error: [Errno 32] Broken pipe
2020-02-13 06:11:33.786 T:3393975104   ERROR: Skin Helper Service --> Exception in resources.lib.webservice ! --> [Errno 32] Broken pipe
2020-02-13 06:12:53.024 T:4094976016   ERROR: Control 1000 in window 13002 has been asked to focus, but it can't

Eu cred ca-mi lipseste un step ... ce sa faca cu rezultatele gasite. Doar ca n-am idee ce anume trebuie sa mai adaug. Am incercat si action: "ACTIVATE", e la fel.

**Comment by arlekyn2** [comment]
Am remarcat schimbarea la cautarea din trakt - acum cauta sezon/episod, dar si aici e o mica problema. Daca episodul nu are torrent separat si e inclus intr-un season pack, iar FL nu returneaza rezultate (pt ca nu sunt), ar fi bine daca scriptul ar repeta cautarea eliminand episod no, doar dupa sezon. Asta ca sugestie...
Mai important, pe ultima versiune de MRSP nu mai merge streaming-ul prin torrenter. Pot in continuare sa descarc cu transmission din context menu si apoi sa vizionez torrentul cand e descarcat tot. Dar daca incerc sa-l vad in modul streaming, primesc torrenter error - am incercat si torrent2http si python-libtorrent players.
Logul arata asa:
2020-02-15 09:08:13.667 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: dirname:/storage/.kodi/temp/xbmcup/script.module.libtorrent/python_libtorrent
2020-02-15 09:08:13.667 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: set_version: no sizefile at /storage/.kodi/addons/script.module.libtorrent/python_libtorrent/linux_armv7/1.1.7 back to default 1.1.7
2020-02-15 09:08:13.667 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: set_version: no default at /storage/.kodi/addons/script.module.libtorrent/python_libtorrent/linux_armv7/1.1.7 searching for any version
2020-02-15 09:08:13.668 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: set_version: chose 1.0.6 out of ['1.0.7', '1.1.0', '1.0.9', '1.1.1', '0.16.19', '1.0.6']
2020-02-15 09:08:13.668 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: platform: {'os': 'linux', 'message': ['As far as I know you can compile python-libtorrent for ARMv6-7.', 'You should search for "OneEvil\'s OpenELEC libtorrent" or use Ace Stream.'], 'version': '1.0.6', 'arch': 'armv7', 'system': 'linux_armv7'}
2020-02-15 09:08:13.668 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: os: ('Linux', 'CoreELEC', '3.14.29', '#1 SMP Wed Nov 27 06:02:54 GMT 2019', 'aarch64')
2020-02-15 09:08:13.668 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: ucs4 x86
2020-02-15 09:08:13.669 T:3263157056  NOTICE: ### [python-libtorrent v.1.1.7]: Imported libtorrent v1.0.6.0 from "/storage/.kodi/temp/xbmcup/script.module.libtorrent/python_libtorrent/linux_armv7/1.0.6"
2020-02-15 09:08:19.249 T:3263157056   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: SkorbaLoader instance has no attribute 'torrentFileInfo'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.torrenter/default.py", line 42, in <module>
                                                core.executeAction(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1252, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1604, in playSTRM
                                                self.playTorrent(params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Core.py", line 1515, in playTorrent
                                                self.Player = TorrentPlayer(userStorageDirectory=self.userStorageDirectory, torrentUrl=torrentUrl, params=params)
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Player.py", line 173, in __init__
                                                self.setup_torrent()
                                              File "/storage/.kodi/addons/plugin.video.torrenter/Player.py", line 246, in setup_torrent
                                                self.torrent.startSession()
                                              File "/storage/.kodi/addons/plugin.video.torrenter/SkorbaLoader.py", line 439, in startSession
                                                torrent_info={'ti': self.torrentFileInfo,
                                            AttributeError: SkorbaLoader instance has no attribute 'torrentFileInfo'
                                            -->End of Python script error report<--
2020-02-15 09:08:19.510 T:3311399744   ERROR: GetDirectory - Error getting plugin://plugin.video.torrenter/?action=playSTRM&url=%2Ftmp%2F11b348303c861f85db87ba1c8a4bb94b.torrent&not_download_only=True&seedtransmission=true
2020-02-15 09:08:19.513 T:4093095952   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.torrenter/?action=playSTRM&url=%2Ftmp%2F11b348303c861f85db87ba1c8a4bb94b.torrent&not_download_only=True&seedtransmission=true) failed
2020-02-15 09:11:19.621 T:3430196032  NOTICE: [plugin.video.elementum] [36mDEBU  main         ▶ Notification     [0mGot notification from xbmc/GUI.OnScreensaverActivated: null
2020-02-15 09:12:38.927 T:3430196032  NOTICE: [plugin.video.elementum] INFO  library      ▶ RefreshTrakt     [0mRunning Trakt sync
2020-02-15 09:12:39.861 T:3430196032  NOTICE: [plugin.video.elementum] [36mDEBU  library      ▶ RefreshTrakt     [0mSkipping Trakt sync due to stale activities
2020-02-15 09:12:39.861 T:3430196032  NOTICE: [plugin.video.elementum] INFO  library      ▶ func2            [0mTrakt sync finished in 933.373208ms

**Comment by arlekyn2** [comment]
Update: MRSP player functioneaza, torrenter player tot nu merge. 
La mine torrent2http merge rau, se blocheaza dupa cateva secunde de vizionare si nu-si revine pana nu se termina de descarcat tot torrentul.  Python-libtorrent player mergea bine (cand mergea play cu torrenter).

**Comment by xngsrs** [comment]
@arlekyn2 
Scrii prea multe chestii pe un issue. Pentru probleme separate de cele initiate, deschide alt issue. 
Te rog, nu imi mai spune despre openmeta pentru ca nu o sa ma ocup niciodata de asa ceva.
Problemele pentru care ai deschis issue: 
1- O sa rezolv cand am timp
2- De ce vrei filelist api, cand addonul funtioneaza asa cum e? Api-ul e inutil in momentul asta, pentru mine, si nu merita sa imi bat capul cu el.

Pentru restul problemelor, deschizi alt issue, imi oferi detalii despre sistemul de operare si imi oferi log-ul care sa contina eroarea. Mie imi merge bine, deci nu am cum sa ghicesc.
