### ISSUE TITLE
Eroare TvrPlus 

### ISSUE THREAD

**Issue by staycanuca** [xngsrs/myhobby#3]
Salut.
In TvrPlus nici un meniu nu mai functioneaza.
In log apare umatoarea eroare
`-->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: expected string or buffer
                                            Traceback (most recent call last):
                                              File "E:\Kodi\kodi 17.3\App\portable_data\addons\plugin.video.tvrplus\default.py", line 272, in <module>
                                                parse_menu(url, meniu)
                                              File "E:\Kodi\kodi 17.3\App\portable_data\addons\plugin.video.tvrplus\default.py", line 170, in parse_menu
                                                re.IGNORECASE | re.DOTALL)
                                              File "E:\Kodi\kodi 17.3\App\system\python\Lib\re.py", line 181, in findall
                                                return _compile(pattern, flags).findall(string)
                                            TypeError: expected string or buffer
                                            -->End of Python script error report<--`

Mersi.

**Comment by staycanuca** [comment]
Cred ca pluginul nu are probleme.
Se pare ca isi refac portalul cei de la TVR.

**Comment by xngsrs** [comment]
Salut!
Pana isi revin am lasat doar posturile live.
