### ISSUE TITLE
Kodi 18.8

### ISSUE THREAD

**Issue by mirelsen** [xngsrs/myhobby#61]
Log:

2022-11-08 21:42:30.173 T:8908   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.SyntaxError'>
                                            Error Contents: 'return' with argument inside generator (torrents.py, line 375)
                                            Traceback (most recent call last):
                                              File "C:\Users\io\AppData\Roaming\Kodi\addons\plugin.video.romanianpack\default.py", line 14, in <module>
                                                from resources import Core
                                              File "C:\Users\io\AppData\Roaming\Kodi\addons\plugin.video.romanianpack\resources\Core.py", line 9, in <module>
                                                from resources.lib import streams, torrents
                                            SyntaxError: 'return' with argument inside generator (torrents.py, line 375)
                                            -->End of Python script error report<--
2022-11-08 21:42:30.285 T:3128   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.romanianpack/
2022-11-08 21:42:30.296 T:9316   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.romanianpack/) failed.

**Comment by xngsrs** [comment]
Wright....sorry. 
[Fixed](https://github.com/xngsrs/myhobby/commit/d06f79b0271c7c63d9b637262084cb3886a4e90a)

**Comment by mirelsen** [comment]
Salut. Pe 18.8 si 18.9 ramâne aceeasi eroare dupa addon update. Dupa un kodi update la 19.4 merge. Multumesc oricum!

**Comment by xngsrs** [comment]
Scuze din nou, din viteza am omis ceva...am reparat acum, cum trebuie, in 3856c3450686245183984b17982366dbd4bcda1c

**Comment by machitza** [comment]
am si eu o eroare.... dupa update pe kodi 17.6/linux, 

22:46:44.910 T:139830804180928   ERROR: GetDirectory - Error getting plugin://plugin.video.romanianpack/?Sortby=name&action=recents
22:46:44.911 T:139830804180928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.romanianpack/?Sortby=name&action=recents) failed
22:46:49.352 T:139826669909760   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: __init__() got an unexpected keyword argument 'daemon'
                                            Traceback (most recent call last):
                                              File "/home/gabi/.kodi/addons/plugin.video.romanianpack/default.py", line 30, in <module>
                                                core.executeAction(params)
                                              File "/home/gabi/.kodi/addons/plugin.video.romanianpack/resources/Core.py", line 2022, in executeAction
                                                getattr(self, get("action"))(params)
                                              File "/home/gabi/.kodi/addons/plugin.video.romanianpack/resources/Core.py", line 1441, in recents
                                                result = thread_me(rtype, params, 'recente')
                                              File "/home/gabi/.kodi/addons/plugin.video.romanianpack/resources/functions.py", line 973, in thread_me
                                                worker = Thread(target=search_one, args=(i, queue), daemon=True)
                                            TypeError: __init__() got an unexpected keyword argument 'daemon'
                                            -->End of Python script error report<--
22:46:49.491 T:139830804180928   ERROR: GetDirectory - Error getting plugin://plugin.video.romanianpack/?Sortby=site&action=recents
22:46:49.492 T:139830804180928   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.romanianpack/?Sortby=site&action=recents) failed
22:47:49.222 T:139826585184000 WARNING: CSkinInfo: failed to load skin settings

**Comment by xngsrs** [comment]
@machitza , noroc ca am vazut, intamplator, mesajul tau. In general nu mai intru pe problemele inchise deja. 
Data viitoare, te rog sa deschizi o problema noua ;)
Acum am rezolvat, in d9f26f37e798d0191c01f228416f52581356510d MRSP v1.1.73e
